### ISSUE TITLE
Notice: The order_date function has been called incorrectly. Order properties should not be accessed directly

### ISSUE THREAD

**Issue by soularius** [placetopay/woocommerce-gateway-placetopay#47]
https://github.com/placetopay/woocommerce-gateway-placetopay/blob/fa0f5d82ff2d9ca445bd95ada6334feb787ab3fb/woocommerce/myaccount/orders.php#L82

### Error Description:

The following warning message has been detected in WordPress:

```
Notice: The order_date function has been called incorrectly. Order properties should not be accessed directly. 
Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), 
include('/themes/storefront-child-theme-master/page-my-account.php'), my_account_show, do_shortcode, preg_replace_callback, 
do_shortcode_tag, WC_Shortcodes::my_account, WC_Shortcodes::shortcode_wrapper, WC_Shortcode_My_Account::output, 
WC_Shortcode_My_Account::my_account, wc_get_template, include('/plugins/woocommerce/templates/myaccount/my-account.php'), 
do_action('woocommerce_account_content'), WP_Hook->do_action, WP_Hook->apply_filters, woocommerce_account_content, 
do_action('woocommerce_account_orders_endpoint'), WP_Hook->do_action, WP_Hook->apply_filters, woocommerce_account_orders, 
wc_get_template, include('/plugins/woocommerce-gateway-placetopay/woocommerce/myaccount/orders.php'), 
WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong.
```

This notice was introduced in version 3.0 of WooCommerce. It is recommended to review WordPress debugging for more information.

### Location:
`File: /plugins/woocommerce-gateway-placetopay/woocommerce/myaccount/orders.php `
Line: 82

### Cause of the Error:
The error occurs because there is an attempt to directly access the order_date property of the WC_Order class. 
Since WooCommerce 3.0, object properties should not be accessed directly. Instead, getter methods provided by the class should be used. 
This ensures better data encapsulation and facilitates future updates.

### Proposed Solution:
To fix this error, the direct access to the order_date property should be replaced by the appropriate method get_date_created().

Below is the necessary modification for line 82 of the orders.php file:

Current code (incorrect):
`$order->order_date`

### Corrected code:
`$order->get_date_created()`

The corrected line should look like this:

```
<time datetime="<?php echo date('Y-m-d H:i:s', strtotime($order->get_date_created())); ?>" 
      title="<?php echo esc_attr(strtotime($order->get_date_created())); ?>">
```
      
This change ensures that the order's creation date is accessed properly using the getter method, adhering to WooCommerce's best practices.

![957-999-max](https://github.com/user-attachments/assets/40889be2-b0e3-467a-92b1-2f3de8e4f1e5)

**Comment by freddiegar** [comment]
Great! Thanks for suggestions. It will be fixed in next version

EDIT: I'm coming back from vacation, thanks for waiting
